CREATE TABLE employees (
	id BIGSERIAL PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(50) NOT NULL,
	position VARCHAR(50) NOT NULL,
	email VARCHAR(50) NULL,
	date_of_hire DATE,
	department_id BIGINT
);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (1, 'Bud', 'Truwert', 'Human Resources Manager', 'btruwert0@rambler.ru', '12/17/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (2, 'Genny', 'Slowan', 'Structural Engineer', null, '3/14/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (3, 'Marjie', 'Peatman', 'Health Coach II', 'mpeatman2@simplemachines.org', '8/2/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (4, 'Celestyn', 'Carmel', 'Administrative Officer', null, '2/27/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (5, 'Grier', 'Astlet', 'Quality Control Specialist', null, '11/9/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (6, 'Job', 'Hampton', 'Physical Therapy Assistant', null, '5/2/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (7, 'Dexter', 'MacTrustam', 'GIS Technical Architect', 'dmactrustam6@facebook.com', '12/4/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (8, 'Vera', 'holmes', 'VP Product Management', 'vholmes7@rakuten.co.jp', '9/19/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (9, 'Chantal', 'Thrift', 'Research Associate', 'cthrift8@indiatimes.com', '9/19/2023', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (10, 'Jorey', 'Iacabucci', 'GIS Technical Architect', 'jiacabucci9@e-recht24.de', '3/19/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (11, 'Park', 'Fosdyke', 'Health Coach I', 'pfosdykea@berkeley.edu', '3/31/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (12, 'Phineas', 'Cock', 'Associate Professor', null, '5/13/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (13, 'Nevin', 'Cunrado', 'Programmer IV', 'ncunradoc@tripadvisor.com', '1/24/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (14, 'Fred', 'MacElroy', 'Geological Engineer', 'fmacelroyd@spiegel.de', '5/29/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (15, 'Arabel', 'Whalebelly', 'Staff Scientist', 'awhalebellye@tmall.com', '4/27/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (16, 'Karoly', 'Feare', 'Product Engineer', 'kfearef@zdnet.com', '6/20/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (17, 'Con', 'McClarence', 'Assistant Manager', 'cmcclarenceg@marriott.com', '7/25/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (18, 'Issi', 'Oxford', 'VP Accounting', 'ioxfordh@photobucket.com', '1/13/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (19, 'Sammie', 'Giuroni', 'Senior Sales Associate', 'sgiuronii@springer.com', '1/18/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (20, 'Lenora', 'Mulhill', 'Web Designer II', 'lmulhillj@nih.gov', '5/12/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (21, 'Tiffani', 'Northage', 'Senior Sales Associate', null, '3/28/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (22, 'Walker', 'Wreak', 'Community Outreach Specialist', 'wwreakl@amazon.com', '7/22/2023', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (23, 'Giacopo', 'Morphew', 'Administrative Assistant II', 'gmorphewm@desdev.cn', '1/27/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (24, 'Randolf', 'MacGiolla', 'Community Outreach Specialist', 'rmacgiollan@cisco.com', '4/27/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (25, 'Abel', 'Lauridsen', 'Actuary', 'alauridseno@fema.gov', '7/27/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (26, 'Natasha', 'Kezor', 'VP Product Management', 'nkezorp@cbslocal.com', '5/2/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (27, 'Hillary', 'Tingley', 'Research Assistant IV', 'htingleyq@cdc.gov', '1/4/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (28, 'Lane', 'Senussi', 'Speech Pathologist', 'lsenussir@nature.com', '2/23/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (29, 'Melisse', 'Wrigley', 'Research Assistant III', 'mwrigleys@sphinn.com', '8/17/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (30, 'Lynett', 'Diperaus', 'Electrical Engineer', null, '12/17/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (31, 'Sydney', 'Clitherow', 'Health Coach IV', 'sclitherowu@canalblog.com', '10/22/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (32, 'Pattie', 'Swoffer', 'Product Engineer', 'pswofferv@reddit.com', '10/25/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (33, 'Fitz', 'Frew', 'Assistant Manager', 'ffreww@bizjournals.com', '9/9/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (34, 'Crystie', 'Manklow', 'Quality Control Specialist', null, '10/25/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (35, 'Valentine', 'Tadd', 'Web Developer III', 'vtaddy@goodreads.com', '12/30/2023', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (36, 'Bradney', 'Castan', 'Actuary', 'bcastanz@fotki.com', '6/2/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (37, 'Linell', 'Odde', 'Financial Advisor', 'lodde10@soup.io', '10/29/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (38, 'Lise', 'Howland', 'Office Assistant IV', 'lhowland11@cnet.com', '7/9/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (39, 'Celia', 'Lemerie', 'Technical Writer', null, '11/19/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (40, 'Inesita', 'Orrill', 'Sales Associate', 'iorrill13@baidu.com', '12/16/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (41, 'Eileen', 'Puden', 'Community Outreach Specialist', 'epuden14@elpais.com', '10/8/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (42, 'Aggy', 'Dron', 'Sales Associate', 'adron15@uol.com.br', '8/18/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (43, 'Timofei', 'Belleny', 'Marketing Assistant', 'tbelleny16@google.es', '11/18/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (44, 'Hermione', 'Whenman', 'Business Systems Development Analyst', null, '3/4/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (45, 'Jamima', 'Poley', 'Structural Engineer', 'jpoley18@techcrunch.com', '6/12/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (46, 'Emili', 'Belhome', 'Web Developer II', 'ebelhome19@dedecms.com', '6/24/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (47, 'Dre', 'Snartt', 'Recruiting Manager', 'dsnartt1a@bloomberg.com', '10/2/2023', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (48, 'Anastassia', 'Stranahan', 'Analog Circuit Design manager', 'astranahan1b@skype.com', '3/24/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (49, 'Nicholle', 'Tuffell', 'VP Sales', 'ntuffell1c@tripadvisor.com', '5/4/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (50, 'Torey', 'Jacobovitch', 'Senior Sales Associate', 'tjacobovitch1d@eepurl.com', '3/15/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (51, 'Tildy', 'Bonifas', 'Data Coordinator', 'tbonifas1e@eventbrite.com', '6/18/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (52, 'Bennie', 'Hatz', 'Paralegal', 'bhatz1f@buzzfeed.com', '4/19/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (53, 'Pammy', 'Bettenson', 'Business Systems Development Analyst', null, '1/21/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (54, 'Jerrilee', 'Fryer', 'Assistant Manager', 'jfryer1h@live.com', '4/23/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (55, 'Madel', 'Neeve', 'Analog Circuit Design manager', null, '5/28/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (56, 'Ivy', 'Wallicker', 'Community Outreach Specialist', 'iwallicker1j@godaddy.com', '9/6/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (57, 'Zolly', 'Timblett', 'Programmer III', 'ztimblett1k@over-blog.com', '8/13/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (58, 'Ray', 'Biers', 'Cost Accountant', null, '10/7/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (59, 'Cheryl', 'Siddon', 'VP Accounting', 'csiddon1m@vistaprint.com', '1/22/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (60, 'Niccolo', 'Twigger', 'Recruiter', 'ntwigger1n@businesswire.com', '12/26/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (61, 'Vincenty', 'Pinnell', 'Budget/Accounting Analyst III', null, '4/7/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (62, 'Mitzi', 'Kield', 'Occupational Therapist', 'mkield1p@mayoclinic.com', '9/1/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (63, 'Cristy', 'Woodland', 'Web Designer II', 'cwoodland1q@earthlink.net', '3/28/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (64, 'Jo ann', 'Blind', 'Account Representative IV', 'jblind1r@nhs.uk', '2/17/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (65, 'Shanon', 'McMichan', 'Marketing Assistant', 'smcmichan1s@digg.com', '10/13/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (66, 'Dominique', 'Marmyon', 'Nuclear Power Engineer', 'dmarmyon1t@google.nl', '1/22/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (67, 'Nicolle', 'Meneer', 'Graphic Designer', null, '9/17/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (68, 'Kenyon', 'McIlreavy', 'Actuary', 'kmcilreavy1v@dagondesign.com', '5/15/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (69, 'Theo', 'Beresfore', 'Accounting Assistant II', 'tberesfore1w@walmart.com', '2/28/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (70, 'Emmalee', 'Lydiard', 'Accounting Assistant III', 'elydiard1x@sciencedirect.com', '11/26/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (71, 'Reinaldo', 'Chaston', 'Help Desk Operator', null, '5/24/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (72, 'Carlita', 'Pilley', 'Staff Accountant I', 'cpilley1z@virginia.edu', '10/7/2023', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (73, 'Sheila', 'Somner', 'Occupational Therapist', 'ssomner20@techcrunch.com', '3/14/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (74, 'Miguela', 'Wheelton', 'Nurse', 'mwheelton21@hugedomains.com', '7/26/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (75, 'Dian', 'MacKomb', 'Legal Assistant', 'dmackomb22@dot.gov', '9/30/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (76, 'Arielle', 'Yexley', 'Biostatistician III', null, '10/4/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (77, 'Marchall', 'Wooler', 'Senior Editor', null, '4/21/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (78, 'Lorri', 'Chasle', 'Programmer I', 'lchasle25@theatlantic.com', '1/28/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (79, 'Eddy', 'Baudino', 'VP Accounting', null, '3/28/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (80, 'Ernaline', 'Santora', 'Cost Accountant', null, '7/18/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (81, 'Karlik', 'Van Geffen', 'Quality Control Specialist', 'kvangeffen28@va.gov', '10/14/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (82, 'Darryl', 'Tomson', 'Research Assistant II', 'dtomson29@walmart.com', '12/23/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (83, 'Cyndy', 'Lapworth', 'Teacher', 'clapworth2a@cmu.edu', '5/6/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (84, 'Haskel', 'McGinnis', 'General Manager', 'hmcginnis2b@symantec.com', '1/10/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (85, 'Jordanna', 'Heining', 'Librarian', 'jheining2c@printfriendly.com', '5/16/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (86, 'Zollie', 'De''Vere - Hunt', 'Programmer II', null, '5/4/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (87, 'Olenolin', 'Andreutti', 'Financial Analyst', null, '12/13/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (88, 'Evangeline', 'Exter', 'Tax Accountant', null, '9/14/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (89, 'Lowell', 'Sumpton', 'Geologist III', 'lsumpton2g@xing.com', '1/2/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (90, 'Riobard', 'Bonniface', 'Information Systems Manager', null, '12/26/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (91, 'Bellanca', 'Passe', 'Administrative Officer', 'bpasse2i@spiegel.de', '4/23/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (92, 'Saundra', 'MacCracken', 'Payment Adjustment Coordinator', 'smaccracken2j@instagram.com', '10/28/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (93, 'Chrystel', 'Durdan', 'Executive Secretary', 'cdurdan2k@virginia.edu', '11/11/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (94, 'Winston', 'Glede', 'Paralegal', 'wglede2l@cmu.edu', '4/12/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (95, 'Consolata', 'Worg', 'Associate Professor', 'cworg2m@newyorker.com', '5/25/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (96, 'Jo', 'Jenney', 'Electrical Engineer', 'jjenney2n@csmonitor.com', '11/13/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (97, 'Les', 'Lapping', 'Occupational Therapist', 'llapping2o@walmart.com', '3/23/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (98, 'Nealon', 'Bangle', 'Environmental Tech', null, '7/30/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (99, 'Janna', 'Garside', 'Actuary', null, '6/29/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (100, 'Ingamar', 'Velareal', 'Technical Writer', 'ivelareal2r@weather.com', '3/4/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (101, 'Nedda', 'Dumelow', 'VP Sales', null, '10/29/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (102, 'Sibella', 'Neggrini', 'Quality Control Specialist', 'sneggrini2t@usa.gov', '8/11/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (103, 'Annalee', 'Prynne', 'Help Desk Technician', null, '11/1/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (104, 'Selina', 'Kinkaid', 'Quality Control Specialist', 'skinkaid2v@forbes.com', '6/5/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (105, 'Antonius', 'Hanton', 'Senior Financial Analyst', 'ahanton2w@wp.com', '2/12/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (106, 'Rafaelita', 'Giffen', 'Senior Developer', 'rgiffen2x@ed.gov', '5/19/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (107, 'Helge', 'Haddinton', 'Executive Secretary', 'hhaddinton2y@sun.com', '3/11/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (108, 'Cristal', 'MacBrearty', 'Business Systems Development Analyst', 'cmacbrearty2z@g.co', '10/26/2023', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (109, 'Frasco', 'Abelwhite', 'Legal Assistant', 'fabelwhite30@yellowpages.com', '8/14/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (110, 'Benedikta', 'Weth', 'Recruiting Manager', null, '8/20/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (111, 'Antony', 'Aupol', 'Operator', 'aaupol32@ucla.edu', '1/5/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (112, 'Shawn', 'Cheatle', 'Physical Therapy Assistant', 'scheatle33@nymag.com', '9/18/2023', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (113, 'Chiquita', 'Twamley', 'Developer I', 'ctwamley34@g.co', '8/22/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (114, 'Christyna', 'Beviss', 'Biostatistician I', 'cbeviss35@adobe.com', '8/25/2023', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (115, 'Edgar', 'Coope', 'Health Coach IV', 'ecoope36@oaic.gov.au', '7/3/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (116, 'Farly', 'Girardoni', 'VP Accounting', null, '11/6/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (117, 'Stavro', 'Lidgard', 'Tax Accountant', 'slidgard38@boston.com', '3/16/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (118, 'Nicolais', 'Eymor', 'Teacher', 'neymor39@creativecommons.org', '12/12/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (119, 'Cheryl', 'Anfusso', 'Graphic Designer', null, '7/25/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (120, 'Mikel', 'Hewins', 'Chemical Engineer', 'mhewins3b@disqus.com', '3/22/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (121, 'Angelica', 'Maris', 'Statistician I', 'amaris3c@t-online.de', '7/12/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (122, 'Beverly', 'Allan', 'Environmental Specialist', 'ballan3d@geocities.com', '3/7/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (123, 'Padraic', 'Skull', 'Quality Control Specialist', 'pskull3e@google.nl', '2/28/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (124, 'Phyllida', 'Calow', 'Junior Executive', 'pcalow3f@soup.io', '8/8/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (125, 'Curcio', 'Drinkale', 'Mechanical Systems Engineer', null, '5/10/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (126, 'Kath', 'Aleso', 'Media Manager IV', 'kaleso3h@nyu.edu', '9/3/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (127, 'Sonnie', 'Elsegood', 'Systems Administrator I', 'selsegood3i@cornell.edu', '6/8/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (128, 'Tierney', 'Consadine', 'General Manager', null, '9/23/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (129, 'Alikee', 'Hames', 'Paralegal', 'ahames3k@smh.com.au', '7/4/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (130, 'Alfy', 'Melladew', 'Design Engineer', 'amelladew3l@163.com', '8/29/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (131, 'Filippa', 'Briand', 'VP Sales', 'fbriand3m@e-recht24.de', '4/14/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (132, 'Sunny', 'Rozea', 'Marketing Manager', null, '3/23/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (133, 'Kelsi', 'Grime', 'Payment Adjustment Coordinator', null, '12/21/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (134, 'Fanni', 'Deare', 'Assistant Professor', 'fdeare3p@apache.org', '3/21/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (135, 'Gawain', 'Karppi', 'Financial Analyst', 'gkarppi3q@huffingtonpost.com', '5/7/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (136, 'Andrei', 'Ajsik', 'Computer Systems Analyst I', 'aajsik3r@over-blog.com', '4/1/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (137, 'Nicholas', 'Hache', 'Research Assistant IV', 'nhache3s@chronoengine.com', '3/30/2024', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (138, 'Hurlee', 'Overshott', 'VP Accounting', 'hovershott3t@pagesperso-orange.fr', '9/3/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (139, 'Britney', 'Chipping', 'Internal Auditor', 'bchipping3u@phoca.cz', '7/9/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (140, 'Flem', 'Hinckes', 'Teacher', 'fhinckes3v@illinois.edu', '8/29/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (141, 'Kristofor', 'Splevings', 'Account Coordinator', 'ksplevings3w@washington.edu', '7/4/2024', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (142, 'Desirae', 'Dottrell', 'Marketing Assistant', 'ddottrell3x@google.nl', '9/23/2023', 7);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (143, 'Ethelin', 'Dighton', 'Payment Adjustment Coordinator', null, '8/31/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (144, 'Cicely', 'Stimson', 'Senior Sales Associate', 'cstimson3z@about.com', '11/16/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (145, 'Feodora', 'Jouandet', 'Nurse', 'fjouandet40@businesswire.com', '3/23/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (146, 'Gabby', 'Fawdrey', 'Software Consultant', 'gfawdrey41@wordpress.com', '1/30/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (147, 'Madison', 'Christofe', 'Accountant III', 'mchristofe42@chronoengine.com', '9/7/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (148, 'Kathleen', 'Biddell', 'Administrative Assistant III', 'kbiddell43@hugedomains.com', '5/26/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (149, 'Lilias', 'Andrichuk', 'Engineer IV', 'landrichuk44@flickr.com', '9/1/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (150, 'Carlynn', 'Fould', 'Senior Developer', 'cfould45@theglobeandmail.com', '4/1/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (151, 'Carmelia', 'Pach', 'Web Designer IV', 'cpach46@123-reg.co.uk', '3/25/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (152, 'Ninette', 'Farress', 'VP Product Management', null, '1/26/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (153, 'Dreddy', 'Handaside', 'Actuary', null, '11/16/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (154, 'Edvard', 'Carlo', 'Data Coordinator', null, '4/7/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (155, 'Alvina', 'Beaten', 'Occupational Therapist', null, '9/26/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (156, 'Neilla', 'O''Lagen', 'Information Systems Manager', 'nolagen4b@google.co.jp', '8/18/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (157, 'Shelba', 'Newcom', 'Data Coordinator', 'snewcom4c@umn.edu', '4/30/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (158, 'Elia', 'Ogus', 'Account Representative IV', null, '3/27/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (159, 'Juanita', 'Pendlebury', 'Software Test Engineer III', 'jpendlebury4e@ameblo.jp', '11/19/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (160, 'Talbot', 'Tupman', 'Staff Accountant II', null, '9/8/2023', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (161, 'Corrine', 'Bocock', 'Sales Associate', 'cbocock4g@forbes.com', '10/1/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (162, 'Kelley', 'Torrance', 'Compensation Analyst', 'ktorrance4h@qq.com', '3/8/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (163, 'Vitia', 'Boughton', 'Electrical Engineer', 'vboughton4i@businessinsider.com', '8/10/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (164, 'Etti', 'Scotsbrook', 'Environmental Tech', 'escotsbrook4j@reddit.com', '6/2/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (165, 'Cindy', 'Sicily', 'Actuary', 'csicily4k@bravesites.com', '1/7/2024', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (166, 'Tynan', 'Sirman', 'Information Systems Manager', null, '4/19/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (167, 'Dannie', 'Stanyan', 'Editor', 'dstanyan4m@rambler.ru', '11/24/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (168, 'Ethyl', 'Colten', 'Geological Engineer', null, '12/14/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (169, 'Alister', 'Matson', 'Senior Cost Accountant', null, '5/19/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (170, 'Wayne', 'Branchet', 'VP Quality Control', 'wbranchet4p@prweb.com', '11/2/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (171, 'Dion', 'Arnaudet', 'Nurse Practicioner', null, '4/8/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (172, 'Aloise', 'Dillicate', 'Registered Nurse', 'adillicate4r@princeton.edu', '8/9/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (173, 'Quinlan', 'Whapples', 'VP Product Management', 'qwhapples4s@behance.net', '1/17/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (174, 'Elyn', 'Meddings', 'Nurse Practicioner', null, '12/17/2023', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (175, 'Arabele', 'O''Nion', 'Research Associate', 'aonion4u@newyorker.com', '3/19/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (176, 'Chrysler', 'Klambt', 'Civil Engineer', 'cklambt4v@bigcartel.com', '1/7/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (177, 'Pavla', 'Thwaites', 'Media Manager I', null, '2/29/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (178, 'Scotty', 'Houndson', 'Professor', 'shoundson4x@walmart.com', '5/13/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (179, 'Stefanie', 'Cornfoot', 'Assistant Professor', 'scornfoot4y@chron.com', '5/2/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (180, 'Eran', 'Van Hesteren', 'Desktop Support Technician', null, '3/30/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (181, 'Theo', 'Ingledew', 'Legal Assistant', 'tingledew50@reddit.com', '3/15/2024', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (182, 'Jeffry', 'Quinion', 'Safety Technician IV', 'jquinion51@github.io', '7/23/2023', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (183, 'Ambros', 'Strooband', 'Nuclear Power Engineer', null, '1/24/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (184, 'Leese', 'Caroll', 'Geologist IV', 'lcaroll53@people.com.cn', '6/16/2024', 6);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (185, 'Salomi', 'Hanbury', 'Software Consultant', 'shanbury54@google.cn', '8/19/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (186, 'Bernadina', 'Davoren', 'Software Consultant', 'bdavoren55@patch.com', '8/14/2023', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (187, 'Sayer', 'Mardee', 'Director of Sales', null, '7/29/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (188, 'Joelle', 'Gabbot', 'Assistant Professor', 'jgabbot57@squarespace.com', '3/7/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (189, 'Robinett', 'Fibbens', 'Legal Assistant', 'rfibbens58@360.cn', '5/19/2024', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (190, 'Naomi', 'Hurdman', 'Account Representative I', 'nhurdman59@disqus.com', '12/3/2023', 10);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (191, 'Anatol', 'Le Pine', 'Administrative Officer', 'alepine5a@squarespace.com', '10/15/2023', 5);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (192, 'Brook', 'Windows', 'Assistant Professor', 'bwindows5b@irs.gov', '4/2/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (193, 'Kalila', 'Jersch', 'Graphic Designer', 'kjersch5c@nba.com', '5/15/2024', 4);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (194, 'Shaine', 'Breissan', 'Research Nurse', null, '3/19/2024', 8);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (195, 'Hoyt', 'Nelthorp', 'Graphic Designer', 'hnelthorp5e@is.gd', '11/11/2023', 3);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (196, 'Hastie', 'Averies', 'Community Outreach Specialist', 'haveries5f@howstuffworks.com', '8/21/2023', 2);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (197, 'Dehlia', 'Josebury', 'Senior Sales Associate', 'djosebury5g@army.mil', '4/1/2024', 9);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (198, 'Brittne', 'Banham', 'Mechanical Systems Engineer', null, '6/25/2024', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (199, 'Fallon', 'Glowach', 'Physical Therapy Assistant', 'fglowach5i@google.ru', '10/30/2023', 1);
insert into employees (id, first_name, last_name, position, email, date_of_hire, department_id) values (200, 'Chantal', 'Radage', 'Marketing Assistant', null, '6/30/2024', 1);
